name: 'Install Docr Action'
description: 'Install a published Docr release'
author: 'NotAShelf'
inputs:
  github-repo:
    description: 'GitHub repository (e.g., owner/repo) to fetch releases from'
    required: true
    default: 'NotAShelf/Docr'
  install-dir:
    description: 'Installation directory'
    required: true
    default: './'
  template-dir:
    description: 'HTML/Css Templates directory'
    required: true
    defualt: 'templates'
  markdown-dir:
    description: 'Markdown directory'
    required: true
    default: 'markdown'
  output-dir:
    description: 'Output directory'
    required: true
    default: 'output'
  github-username:
    description: 'GitHub username'
    required: true
  website-name:
    description: 'Website name'
    required: true
  website-url:
    description: 'Website URL'
    required: true
  website-description:
    description: 'Website description'
    required: true
  timestamps-from-filename:
    description: 'Extract timestamps from filename (true/false)'
    required: true
outputs:
  installed-version:
    description: 'The installed version'
runs:
  using: 'node20'
  main: 'dist/index.js'
